#!/usr/bin/env node
// scripts/csv-to-ts.mjs
// One-shot: read tools/event-build/events.csv + existing src/data/events.ts (for poster paths),
// merge, and re-emit src/data/events.ts.
// Run: node scripts/csv-to-ts.mjs

import path from 'node:path';
import fs   from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const ROOT       = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CSV_PATH   = path.join(ROOT, 'tools', 'event-build', 'events.csv');
const TS_PATH    = path.join(ROOT, 'src', 'data', 'events.ts');
const GITHUB_RAW = 'https://raw.githubusercontent.com/xiaflos/stoa60/main/src/assets/images/posters';

// ── CSV parser (handles quoted fields containing commas) ───────────────────
function parseCSVLine(line) {
  const fields = [];
  let cur = '', inQ = false;
  for (const ch of line) {
    if (ch === '"') { inQ = !inQ; }
    else if (ch === ',' && !inQ) { fields.push(cur); cur = ''; }
    else { cur += ch; }
  }
  fields.push(cur);
  return fields;
}

function parseCSV(raw) {
  const lines = raw.split(/\r?\n/).filter(l => l.trim());
  const headers = parseCSVLine(lines[0]);
  return lines.slice(1).map(line => {
    const vals = parseCSVLine(line);
    return Object.fromEntries(headers.map((h, i) => [h.trim(), (vals[i] ?? '').trim()]));
  });
}

// ── Field parsers ──────────────────────────────────────────────────────────
function parseOrganiser(raw) {
  if (!raw || !raw.trim()) return ['stoa60'];
  // Accept both comma-separated (possibly quoted) and semicolon-separated
  return raw.split(/[,;]/).map(s => s.trim()).filter(Boolean);
}

function parseEventType(raw) {
  const t = raw ? raw.trim() : '';
  if (!t) return 'gig';
  // Preserve the user's capitalisation; just normalise all-lowercase single words
  // that clearly represent a category (bar → Bar, party → Party)
  const lower = t.toLowerCase();
  if (lower === 'bar')    return 'Bar';
  if (lower === 'party')  return 'Party';
  return t;  // keep as typed for multi-word / proper names
}

function parseBands(row) {
  return ['band_1','band_2','band_3','band_4','band_5','band_6']
    .map(k => (row[k] ?? '').trim())
    .filter(Boolean);
}

function parseBandLinks(raw) {
  if (!raw || !raw.trim()) return {};
  const result = {};
  for (const part of raw.split('|')) {
    const idx = part.indexOf('=');
    if (idx > 0) {
      const name = part.slice(0, idx).trim();
      const url  = part.slice(idx + 1).trim();
      if (name && url) result[name] = url;
    }
  }
  return result;
}

// ── Load existing events.ts to extract poster paths ───────────────────────
async function loadExistingPosters() {
  let raw;
  try { raw = await fs.readFile(TS_PATH, 'utf8'); }
  catch { return new Map(); }

  // Extract JSON array from the TS source
  const start = raw.indexOf('= [');
  const end   = raw.lastIndexOf('];');
  if (start === -1 || end === -1) return new Map();
  let json;
  try { json = JSON.parse(raw.slice(start + 2, end + 1)); }
  catch { return new Map(); }

  // Key: "date|location" → { poster, recordings }[]
  // (multiple events can share a date, different location)
  const map = new Map();
  for (const ev of json) {
    const key = `${ev.date}|${ev.location}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key).push({ poster: ev.poster ?? '', recordings: ev.recordings });
  }
  return map;
}

// ── CSV serialiser (write-back with poster_url column) ────────────────────
function csvField(v) {
  // Quote the field if it contains commas, quotes, or newlines
  const s = String(v ?? '');
  return s.includes(',') || s.includes('"') || s.includes('\n')
    ? `"${s.replace(/"/g, '""')}"` : s;
}

function serializeCsv(rows, events) {
  // Determine the base columns from the original CSV header,
  // replacing any existing poster_url column or appending a new one.
  const BAND_COLS = ['band_1','band_2','band_3','band_4','band_5','band_6'];
  const BASE_COLS = ['date','location','organiser','Title',...BAND_COLS,'poster_url','links'];

  const header = BASE_COLS.join(',');

  const lines = rows.map((row, i) => {
    const ev      = events[i];
    const poster  = ev?.poster ?? '';
    const url     = poster ? `${GITHUB_RAW}/${poster}` : '';

    const fields = [
      row.date           ?? '',
      row.location       ?? '',
      row.organiser      ?? '',
      ev?.eventType      ?? row.Title ?? '',
      ...BAND_COLS.map(k => row[k] ?? ''),
      url,
      row.links          ?? '',
    ];
    return fields.map(csvField).join(',');
  });

  return [header, ...lines].join('\r\n') + '\r\n';
}

// ── TypeScript serialiser ─────────────────────────────────────────────────
function serializeTs(events) {
  const HEADER = `// AUTO-GENERATED by scripts/csv-to-ts.mjs — do not edit by hand.
// Source: tools/event-build/events.csv
// Re-run \`node scripts/csv-to-ts.mjs\` to regenerate.

export type Location =
  | 'underground' | 'karabolas' | 'voutes'
  | 'xenia' | 'georgiadis' | 'evangelismos' | 'walls';

export type Organiser =
  | 'stoa60' | 'ba2037' | 'rastapank'
  | 'vomvos' | 'tameiosolidarity';

export interface Recording { name: string; url: string; }

export interface Event {
  date: string;
  bands: string[];
  rawTitle: string;
  eventType: string;       // 'gig' | 'Bar' | 'Party' | 'Soundsystem' | ...
  location: Location;
  organiser: Organiser[];
  poster: string;
  bandLinks?: Record<string, string>;
  recordings?: Recording[];
}

export const events: Event[] = `;

  const body = JSON.stringify(events, null, 2);
  return HEADER + body + ';\n';
}

// ── Main ──────────────────────────────────────────────────────────────────
async function main() {
  const raw        = await fs.readFile(CSV_PATH, 'utf8');
  const rows       = parseCSV(raw);
  const posterMap  = await loadExistingPosters();

  // Track how many poster look-ups succeed / fail
  let matched = 0, unmatched = 0;

  // Some dates have two events (e.g. 2018-02-17 has underground + voutes).
  // Keep a "used" counter per date+location key so we don't double-assign.
  const used = new Map();

  const events = rows.map(row => {
    const date      = row.date.trim();
    const location  = row.location.trim();
    const organiser = parseOrganiser(row.organiser);
    const eventType = parseEventType(row.Title ?? '');
    const bands     = parseBands(row);
    const rawTitle  = bands.join(', ');

    // Poster look-up: try "date|location" first, then "date|underground" as fallback
    let poster = '';
    let recordings;
    const key1 = `${date}|${location}`;
    const key2 = `${date}|underground`;

    for (const key of [key1, key2]) {
      const arr = posterMap.get(key);
      if (arr) {
        const idx = used.get(key) ?? 0;
        if (idx < arr.length) {
          poster     = arr[idx].poster ?? '';
          recordings = arr[idx].recordings;
          used.set(key, idx + 1);
          matched++;
          break;
        }
      }
    }
    if (!poster) unmatched++;

    const bandLinks = parseBandLinks(row.links ?? '');
    const ev = { date, bands, rawTitle, eventType, location, organiser, poster };
    if (Object.keys(bandLinks).length > 0) ev.bandLinks = bandLinks;
    if (recordings) ev.recordings = recordings;
    return ev;
  });

  await fs.writeFile(TS_PATH, serializeTs(events), 'utf8');
  await fs.writeFile(CSV_PATH, serializeCsv(rows, events), 'utf8');

  console.log(`[csv-to-ts] ${events.length} events written to events.ts + events.csv`);
  console.log(`  posters matched: ${matched}  |  no poster: ${unmatched}`);

  // Summary of new field values
  const locations  = [...new Set(events.map(e => e.location))].sort();
  const organisers = [...new Set(events.flatMap(e => e.organiser))].sort();
  const types      = [...new Set(events.map(e => e.eventType))].sort();
  console.log('  locations:', locations.join(', '));
  console.log('  organisers:', organisers.join(', '));
  console.log('  event types:', types.join(', '));
}

main().catch(err => { console.error(err); process.exit(1); });
