// AUTO-GENERATED by scripts/csv-to-ts.mjs — do not edit by hand.
// Source: tools/event-build/events.csv
// Re-run `node scripts/csv-to-ts.mjs` to regenerate.

export type Location =
  | 'underground' | 'karabolas' | 'voutes'
  | 'xenia' | 'georgiadis' | 'evangelismos' | 'walls';

export type Organiser =
  | 'stoa60' | 'ba2037' | 'rastapank'
  | 'vomvos' | 'tameiosolidarity';

export interface Recording { name: string; url: string; }

export interface Event {
  date: string;
  bands: string[];
  rawTitle: string;
  eventType: string;       // 'gig' | 'Bar' | 'Party' | 'Soundsystem' | ...
  location: Location;
  organiser: Organiser[];
  poster: string;
  bandLinks?: Record<string, string>;
  recordings?: Recording[];
}

export const events: Event[] = [
  {
    "date": "2026-05-16",
    "bands": [
      "ΚΑΘΑΡΟΣ ΧΑΛΚΟΣ",
      "ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ"
    ],
    "rawTitle": "ΚΑΘΑΡΟΣ ΧΑΛΚΟΣ, ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-05-16_kathares-arkoudes.jpg",
    "bandLinks": {
      "ΚΑΘΑΡΟΣ ΧΑΛΚΟΣ": "https://katharoschalkos.bandcamp.com/album/-",
      "ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ": "https://www.youtube.com/watch?v=aArwHqZA-7Y"
    }
  },
  {
    "date": "2026-05-09",
    "bands": [
      "DISMISS",
      "THYMICS"
    ],
    "rawTitle": "DISMISS, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-05-09_thymics.jpg",
    "bandLinks": {
      "DISMISS": "https://dismissband.bandcamp.com/music",
      "THYMICS": "https://thymics.bandcamp.com/album/nothing"
    }
  },
  {
    "date": "2026-05-02",
    "bands": [
      "ΣΟΜΑ",
      "MALHOTRA"
    ],
    "rawTitle": "ΣΟΜΑ, MALHOTRA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-05-02_somalhotra.jpg",
    "bandLinks": {
      "ΣΟΜΑ": "https://somamesoma.bandcamp.com/music",
      "MALHOTRA": "https://malhotra.bandcamp.com/album/ruler-sun"
    }
  },
  {
    "date": "2026-04-25",
    "bands": [
      "JUNKHEART",
      "ΠΟΝΤΙΚΙΑ"
    ],
    "rawTitle": "JUNKHEART, ΠΟΝΤΙΚΙΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-04-25_junkheart_pontikia.jpg"
  },
  {
    "date": "2026-04-18",
    "bands": [
      "ΑΧΕΟΝ",
      "VEIL OMEGA"
    ],
    "rawTitle": "ΑΧΕΟΝ, VEIL OMEGA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-04-18_axeon_veil2.jpg"
  },
  {
    "date": "2026-04-01",
    "bands": [
      "SHORT DAYS",
      "ΕΝΤΕΡΟΝ ΗΜΙΣΥ"
    ],
    "rawTitle": "SHORT DAYS, ΕΝΤΕΡΟΝ ΗΜΙΣΥ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-04-01_shortdays.jpg"
  },
  {
    "date": "2026-03-27",
    "bands": [
      "STOA SUBATOMIC vol.1"
    ],
    "rawTitle": "STOA SUBATOMIC vol.1",
    "eventType": "Soundsystem",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-03-27_subatomic.jpg"
  },
  {
    "date": "2026-03-21",
    "bands": [
      "AETHERIAN",
      "FLAMECORE"
    ],
    "rawTitle": "AETHERIAN, FLAMECORE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-03-21_aetherian.jpg"
  },
  {
    "date": "2026-03-14",
    "bands": [
      "BLOODTRACE",
      "YOUTHCRUSHER"
    ],
    "rawTitle": "BLOODTRACE, YOUTHCRUSHER",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-03-14_youth.jpg"
  },
  {
    "date": "2026-03-07",
    "bands": [
      "INVALTA",
      "ΒΑΚΙΡΤΖΙΑΝ"
    ],
    "rawTitle": "INVALTA, ΒΑΚΙΡΤΖΙΑΝ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-03-07_invalta.jpg"
  },
  {
    "date": "2026-02-28",
    "bands": [
      "KRATS",
      "HAND & LEG"
    ],
    "rawTitle": "KRATS, HAND & LEG",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-02-28_kratsHand.jpg"
  },
  {
    "date": "2026-02-14",
    "bands": [
      "OMEGA MONOLITH",
      "CALF",
      "LIVING UNDER DRONES"
    ],
    "rawTitle": "OMEGA MONOLITH, CALF, LIVING UNDER DRONES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-02-14_omega.jpg"
  },
  {
    "date": "2026-02-07",
    "bands": [
      "ZERO CHANCE",
      "OTOΜΠΡΙΤΣΙ ΜΟΤΟΡΙ"
    ],
    "rawTitle": "ZERO CHANCE, OTOΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-02-07_otompritsi.jpg"
  },
  {
    "date": "2026-01-31",
    "bands": [
      "STOLEN MIC",
      "ΣΗΜΑΔΙ",
      "ΔΡΑΜΑ ΚΩΜΙΚΟΥ",
      "ΧΩΡΙΣ ΚΑΝΟΝΑ",
      "WONE",
      "ΦΛΥΑΡΙΑ"
    ],
    "rawTitle": "STOLEN MIC, ΣΗΜΑΔΙ, ΔΡΑΜΑ ΚΩΜΙΚΟΥ, ΧΩΡΙΣ ΚΑΝΟΝΑ, WONE, ΦΛΥΑΡΙΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-01-31_stolen.jpg"
  },
  {
    "date": "2026-01-24",
    "bands": [
      "KVADRAT",
      "1000DEAD"
    ],
    "rawTitle": "KVADRAT, 1000DEAD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-01-24_kvadrat.jpg"
  },
  {
    "date": "2026-01-17",
    "bands": [
      "THE KLAMMERS",
      "MELLOW LIZARD"
    ],
    "rawTitle": "THE KLAMMERS, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-01-17_klammers.jpg"
  },
  {
    "date": "2026-01-10",
    "bands": [
      "DOT ON EARTH",
      "LUSTTONE"
    ],
    "rawTitle": "DOT ON EARTH, LUSTTONE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2026-01-10_dotonearth.jpg"
  },
  {
    "date": "2025-12-20",
    "bands": [
      "DARKNESS BEFORE CHRISTMAS"
    ],
    "rawTitle": "DARKNESS BEFORE CHRISTMAS",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-12-20_darkness.jpg"
  },
  {
    "date": "2025-12-13",
    "bands": [
      "DURY DAVA",
      "ACID ROOTS"
    ],
    "rawTitle": "DURY DAVA, ACID ROOTS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-12-13_dury.jpg"
  },
  {
    "date": "2025-12-06",
    "bands": [
      "BROKEN ELECTRONIX NIGHT PT.II"
    ],
    "rawTitle": "BROKEN ELECTRONIX NIGHT PT.II",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-12-06_broken.jpg"
  },
  {
    "date": "2025-12-04",
    "bands": [
      "NIGHT OF THE DEMON VOL. 2"
    ],
    "rawTitle": "NIGHT OF THE DEMON VOL. 2",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-12-04_night-of-the-demon-vol2.jpg"
  },
  {
    "date": "2025-11-29",
    "bands": [
      "GNAAL",
      "SACHMIS CULT"
    ],
    "rawTitle": "GNAAL, SACHMIS CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-11-29_gnaal.jpg"
  },
  {
    "date": "2025-11-22",
    "bands": [
      "GYNOID",
      "DRUID"
    ],
    "rawTitle": "GYNOID, DRUID",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-11-22_gynoid.jpg"
  },
  {
    "date": "2025-11-15",
    "bands": [
      "SONS OF ZEVEDEUS",
      "ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ"
    ],
    "rawTitle": "SONS OF ZEVEDEUS, ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-11-15_zevedeus.jpg"
  },
  {
    "date": "2025-11-09",
    "bands": [
      "MEMORY",
      "BABY CULT"
    ],
    "rawTitle": "MEMORY, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-11-09_memory.jpg"
  },
  {
    "date": "2025-10-11",
    "bands": [
      "CHAOTIC END",
      "RAPTURE"
    ],
    "rawTitle": "CHAOTIC END, RAPTURE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-10-11_chaotic.jpg"
  },
  {
    "date": "2025-10-04",
    "bands": [
      "PEPLO",
      "HUMACHINES"
    ],
    "rawTitle": "PEPLO, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-10-04_peplo.jpg"
  },
  {
    "date": "2025-09-07",
    "bands": [
      "KRAV BOCA",
      "AEON",
      "THYMICS"
    ],
    "rawTitle": "KRAV BOCA, AEON, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2025-2026/2025-09-07_kravboca.jpg"
  },
  {
    "date": "2025-05-24",
    "bands": [
      "DUB KARAVOLAS"
    ],
    "rawTitle": "DUB KARAVOLAS",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-05-24_reggaedub.jpg"
  },
  {
    "date": "2025-05-17",
    "bands": [
      "KATAXNIA",
      "ΦΟΡΜΟΛΗ"
    ],
    "rawTitle": "KATAXNIA, ΦΟΡΜΟΛΗ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-05-17_kataxnia-formoli.jpg"
  },
  {
    "date": "2025-05-10",
    "bands": [
      "SCARFLOOD"
    ],
    "rawTitle": "SCARFLOOD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-05-10_scarflood.jpg"
  },
  {
    "date": "2025-05-03",
    "bands": [
      "HAY STEALTHY",
      "ΠΟΝΤΙΚΙΑ"
    ],
    "rawTitle": "HAY STEALTHY, ΠΟΝΤΙΚΙΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-05-03_hay-stealthy-pontikia.jpg"
  },
  {
    "date": "2025-05-02",
    "bands": [
      "CRUCIFIXION BAR"
    ],
    "rawTitle": "CRUCIFIXION BAR",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-05-02_crucifixion.jpg"
  },
  {
    "date": "2025-04-26",
    "bands": [
      "ΜΕΓΑΛΗ ΦΥΓΗ",
      "THYMICS"
    ],
    "rawTitle": "ΜΕΓΑΛΗ ΦΥΓΗ, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-04-26_megali-fygi-thymics.jpg"
  },
  {
    "date": "2025-04-05",
    "bands": [
      "MOTORDEATH",
      "CHAOTIC"
    ],
    "rawTitle": "MOTORDEATH, CHAOTIC",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-04-05_motordeath-chaotic.jpg"
  },
  {
    "date": "2025-03-29",
    "bands": [
      "TYPHUS",
      "AXEON"
    ],
    "rawTitle": "TYPHUS, AXEON",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-03-29_typhus-axeon.jpg"
  },
  {
    "date": "2025-03-22",
    "bands": [
      "ΑΝΗΦΟΡΑ",
      "ΝΤΕΡΤΙ DANCING"
    ],
    "rawTitle": "ΑΝΗΦΟΡΑ, ΝΤΕΡΤΙ DANCING",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-03-22_anifora-nterti-dancing.jpg"
  },
  {
    "date": "2025-03-08",
    "bands": [
      "FALOODA",
      "THE DEPRESSANTS"
    ],
    "rawTitle": "FALOODA, THE DEPRESSANTS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-03-08_falooda-the-depressants.jpg"
  },
  {
    "date": "2025-03-01",
    "bands": [
      "ΑΔΑΕΙΣ",
      "ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ"
    ],
    "rawTitle": "ΑΔΑΕΙΣ, ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-03-01_adaeis_afiloxeno_soma.jpg"
  },
  {
    "date": "2025-02-22",
    "bands": [
      "YOVEL",
      "GNAAL"
    ],
    "rawTitle": "YOVEL, GNAAL",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-02-22_yovel-gnaal_fb.jpg"
  },
  {
    "date": "2025-02-15",
    "bands": [
      "TAYLOR SAVAGE",
      "OLA VIA",
      "SIRAP",
      "OUROBOROS"
    ],
    "rawTitle": "TAYLOR SAVAGE, OLA VIA, SIRAP, OUROBOROS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-02-15_taylor-savage-ollavia-sirap-ouroboros.jpg"
  },
  {
    "date": "2025-02-08",
    "bands": [
      "ΣΑΙΚΑ"
    ],
    "rawTitle": "ΣΑΙΚΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-02-08_saika.jpg"
  },
  {
    "date": "2025-01-24",
    "bands": [
      "CUCUMBA",
      "MELLOW LIZARD"
    ],
    "rawTitle": "CUCUMBA, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-01-24_cucumba-mellow-lizard.jpg"
  },
  {
    "date": "2025-01-18",
    "bands": [
      "KALTE NACHT",
      "INCIRRINA",
      "HUMACHINES"
    ],
    "rawTitle": "KALTE NACHT, INCIRRINA, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-01-18_kalte-nacht-incirrina-humachines.jpg"
  },
  {
    "date": "2025-01-11",
    "bands": [
      "ΤΖΟΝΙ ΜΠΙ",
      "BLACK SPIRIT X ACE",
      "GEE THREE"
    ],
    "rawTitle": "ΤΖΟΝΙ ΜΠΙ, BLACK SPIRIT X ACE, GEE THREE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2025-01-11_tzoni-mpi-black-spirit-x-ace-gee-three.jpg"
  },
  {
    "date": "2024-12-14",
    "bands": [
      "NOTHING THRIVES",
      "THYMICS"
    ],
    "rawTitle": "NOTHING THRIVES, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-12-14_nothing-thrives-thymics.jpg"
  },
  {
    "date": "2024-12-13",
    "bands": [
      "ΤΣΙΡΙΝΤΣΑΝΤΣΟΥΛΕΣ"
    ],
    "rawTitle": "ΤΣΙΡΙΝΤΣΑΝΤΣΟΥΛΕΣ",
    "eventType": "Theatre",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-12-13_theatriko.jpg"
  },
  {
    "date": "2024-12-12",
    "bands": [
      "ΕΟΡΤΑΣΤΙΚΟ ΜΠΑΡ"
    ],
    "rawTitle": "ΕΟΡΤΑΣΤΙΚΟ ΜΠΑΡ",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-12-12_eortastiko.jpg"
  },
  {
    "date": "2024-12-07",
    "bands": [
      "BUS THE UNKNOWN SECRETARY",
      "COSMIC PLUNGE"
    ],
    "rawTitle": "BUS THE UNKNOWN SECRETARY, COSMIC PLUNGE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-12-07_bus-the-unknown-secretary-cosmic-plunge.jpg"
  },
  {
    "date": "2024-11-30",
    "bands": [
      "THE VULCAN ITCH",
      "KALYVA"
    ],
    "rawTitle": "THE VULCAN ITCH, KALYVA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-11-30_the-vulcan-itch-kalyva.jpg"
  },
  {
    "date": "2024-11-23",
    "bands": [
      "THE SEXY CHRISTIANS",
      "BABY CULT"
    ],
    "rawTitle": "THE SEXY CHRISTIANS, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-11-23_the-sexy-christians-baby-cult.jpg"
  },
  {
    "date": "2024-11-16",
    "bands": [
      "THE MAN AND HIS FAILURES",
      "PRE-EMPTIVE STRIKE 0.1",
      "ASYLUM PROMISES"
    ],
    "rawTitle": "THE MAN AND HIS FAILURES, PRE-EMPTIVE STRIKE 0.1, ASYLUM PROMISES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-11-16_the-man-and-his-failures-pre-emptive-strike-01-asylum-promises.jpg"
  },
  {
    "date": "2024-11-09",
    "bands": [
      "ΜΟΡΜΩ",
      "CHAOTIC"
    ],
    "rawTitle": "ΜΟΡΜΩ, CHAOTIC",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-11-09_mormo-chaotic.jpg"
  },
  {
    "date": "2024-11-02",
    "bands": [
      "ΔΡΑΜΑ ΚΩΜΙΚΟΥ & THE DRAMOULINS",
      "BLACK SPIRIT",
      "ΛΟΓΟΥ ΧΑΡΙΝ"
    ],
    "rawTitle": "ΔΡΑΜΑ ΚΩΜΙΚΟΥ & THE DRAMOULINS, BLACK SPIRIT, ΛΟΓΟΥ ΧΑΡΙΝ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-11-02_drama-komikoy-and-the-drumoulins-black-spirit-logoy-charin.jpg"
  },
  {
    "date": "2024-10-26",
    "bands": [
      "ΣΤΟΜΑ",
      "FETA NAGASAKI"
    ],
    "rawTitle": "ΣΤΟΜΑ, FETA NAGASAKI",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-10-26_stoma-feta-nagasaki.jpg"
  },
  {
    "date": "2024-10-19",
    "bands": [
      "SEER OF THE VOID",
      "OKWAHO"
    ],
    "rawTitle": "SEER OF THE VOID, OKWAHO",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-10-19_seer-of-the-void-okwaho.jpg"
  },
  {
    "date": "2024-10-12",
    "bands": [
      "MELLOW LIZARD",
      "MANDOLA AND LUTE IMPROV"
    ],
    "rawTitle": "MELLOW LIZARD, MANDOLA AND LUTE IMPROV",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-10-12_mellow lizzrad.jpg"
  },
  {
    "date": "2024-10-05",
    "bands": [
      "ΧΕΙΜΕΡΙΑ ΝΑΡΚΗ",
      "ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ"
    ],
    "rawTitle": "ΧΕΙΜΕΡΙΑ ΝΑΡΚΗ, ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-10-05_xviv-and-sirap-live-electronix.jpg"
  },
  {
    "date": "2024-09-21",
    "bands": [
      "BROKEN ELECTRONIX"
    ],
    "rawTitle": "BROKEN ELECTRONIX",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2024-2025/2024-09-21_broken.jpg"
  },
  {
    "date": "2024-07-20",
    "bands": [
      "ΔΕΜΑΞΗΜΑΜ",
      "PRINCE OF LILLIES"
    ],
    "rawTitle": "ΔΕΜΑΞΗΜΑΜ, PRINCE OF LILLIES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-07-20_demaximam.jpg"
  },
  {
    "date": "2024-07-09",
    "bands": [
      "MY TURN"
    ],
    "rawTitle": "MY TURN",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-07-09_myturn.jpg"
  },
  {
    "date": "2024-06-29",
    "bands": [
      "EL PASO SOUNDSYSTEM"
    ],
    "rawTitle": "EL PASO SOUNDSYSTEM",
    "eventType": "Soundsystem",
    "location": "voutes",
    "organiser": [
      "rastapank"
    ],
    "poster": "2023-2024/2024-06-29_makrofountes_fest.jpg"
  },
  {
    "date": "2024-06-01",
    "bands": [
      "IMPEDANCE",
      "KONOPS",
      "SIRAP"
    ],
    "rawTitle": "IMPEDANCE, KONOPS, SIRAP",
    "eventType": "gig",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "stoa60"
    ],
    "poster": "2023-2024/2024-06-01_impedance_konops.jpg"
  },
  {
    "date": "2024-05-18",
    "bands": [
      "SUN OF NOTHING",
      "KALYVA"
    ],
    "rawTitle": "SUN OF NOTHING, KALYVA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-05-18_sun-of-nothing-kalyva.jpg"
  },
  {
    "date": "2024-05-10",
    "bands": [
      "ΧΕΙΜΕΡΙΑ ΝΑΡΚΗ",
      "ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ"
    ],
    "rawTitle": "ΧΕΙΜΕΡΙΑ ΝΑΡΚΗ, ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-05-10_cheimeria-narki-afiloxeno-soma.jpg"
  },
  {
    "date": "2024-04-20",
    "bands": [
      "FROM JAMAICA TO ENGLAND: A TRIBUTE TO BASS MUSIC PT. II"
    ],
    "rawTitle": "FROM JAMAICA TO ENGLAND: A TRIBUTE TO BASS MUSIC PT. II",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-04-20_jamaica.jpg"
  },
  {
    "date": "2024-04-13",
    "bands": [
      "ΝΕΟΝΑΚΗΣ ΒΑΚΙΡΤΖΙΑΝ",
      "ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ"
    ],
    "rawTitle": "ΝΕΟΝΑΚΗΣ ΒΑΚΙΡΤΖΙΑΝ, ΑΡΚΟΥΔΕΣ ΤΩΝ ΑΓΩΓΩΝ ΤΗΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-04-13_neonakis-kai-vakirtzian-arkoydes-ton-agogon-tis-polykatoikias.jpg"
  },
  {
    "date": "2024-04-05",
    "bands": [
      "$OFT $KULL",
      "MELLOW LIZARD"
    ],
    "rawTitle": "$OFT $KULL, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-04-05_soft-skull-mellow-lizard.jpg"
  },
  {
    "date": "2024-03-30",
    "bands": [
      "THE STRESS",
      "THE FLAT SURFERS"
    ],
    "rawTitle": "THE STRESS, THE FLAT SURFERS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-03-30_the-stress-the-flat-surfers.jpg"
  },
  {
    "date": "2024-03-23",
    "bands": [
      "AMKEN",
      "AXEON"
    ],
    "rawTitle": "AMKEN, AXEON",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-03-23_amken-axeon.jpg"
  },
  {
    "date": "2024-03-15",
    "bands": [
      "ΟΜΙΧΛΗ",
      "THE DEPRESSANTS"
    ],
    "rawTitle": "ΟΜΙΧΛΗ, THE DEPRESSANTS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-03-15_omichli-the-depressants.jpg"
  },
  {
    "date": "2024-03-02",
    "bands": [
      "SCARFLOOD",
      "KALYVA"
    ],
    "rawTitle": "SCARFLOOD, KALYVA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-03-02_nightopfthedemon.jpg"
  },
  {
    "date": "2024-02-24",
    "bands": [
      "SADHUS (THE SMOKING COMMUNITY)",
      "COSMIC PLUNGE"
    ],
    "rawTitle": "SADHUS (THE SMOKING COMMUNITY), COSMIC PLUNGE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-02-24_sadhus.jpg"
  },
  {
    "date": "2024-02-17",
    "bands": [
      "FROM JAMAICA TO ENGLAND: A TRIBUTE TO BASS MUSIC PT. I"
    ],
    "rawTitle": "FROM JAMAICA TO ENGLAND: A TRIBUTE TO BASS MUSIC PT. I",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-02-17_jamaica.jpg"
  },
  {
    "date": "2024-02-10",
    "bands": [
      "COLD I",
      "HUMACHINES"
    ],
    "rawTitle": "COLD I, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-02-10_cold-i-humachines.jpg"
  },
  {
    "date": "2024-02-03",
    "bands": [
      "NIGHT OF THE DEMON"
    ],
    "rawTitle": "NIGHT OF THE DEMON",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-02-03_scarflood-kalyva.jpg"
  },
  {
    "date": "2024-01-27",
    "bands": [
      "ΜΕΘΥΣΜΕΝΑ ΞΩΤΙΚΑ",
      "ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ"
    ],
    "rawTitle": "ΜΕΘΥΣΜΕΝΑ ΞΩΤΙΚΑ, ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-01-27_methysmena-xotika-afiloxeno-soma.jpg"
  },
  {
    "date": "2024-01-19",
    "bands": [
      "PSYCHEDELIC TRIPS TO DEATH",
      "HUMACHINES"
    ],
    "rawTitle": "PSYCHEDELIC TRIPS TO DEATH, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-01-19_PTTD_humachines.jpg"
  },
  {
    "date": "2024-01-13",
    "bands": [
      "ΤΑΦ ΛΑΘΟΣ",
      "TWINSANITY",
      "DJ MICRO"
    ],
    "rawTitle": "ΤΑΦ ΛΑΘΟΣ, TWINSANITY, DJ MICRO",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-01-13_taf-lathos-twinsanity-dj-micro.jpg"
  },
  {
    "date": "2024-01-06",
    "bands": [
      "POST-PUNK VINYL DJ SET"
    ],
    "rawTitle": "POST-PUNK VINYL DJ SET",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2024-01-06_vinyl.jpg"
  },
  {
    "date": "2023-12-23",
    "bands": [
      "MMA ΜΠΑΡ"
    ],
    "rawTitle": "MMA ΜΠΑΡ",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-12-23_bar.jpg"
  },
  {
    "date": "2023-12-16",
    "bands": [
      "CHRONOBOROS",
      "FUTILE MATING TACTICS"
    ],
    "rawTitle": "CHRONOBOROS, FUTILE MATING TACTICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-12-16_chronoboros-futile-mating-tactics.jpg"
  },
  {
    "date": "2023-12-09",
    "bands": [
      "FRENZEE",
      "THYMICS"
    ],
    "rawTitle": "FRENZEE, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-12-09_frenzee-thymics.jpg"
  },
  {
    "date": "2023-12-08",
    "bands": [
      "VENUS VOLCANISM"
    ],
    "rawTitle": "VENUS VOLCANISM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-12-08_venus.jpg"
  },
  {
    "date": "2023-11-25",
    "bands": [
      "FERAL KIDS",
      "THE FLAT SURFERS"
    ],
    "rawTitle": "FERAL KIDS, THE FLAT SURFERS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-11-25_feral-kids-the-flat-surfers.jpg"
  },
  {
    "date": "2023-11-18",
    "bands": [
      "SCI-FI RIVER",
      "ANIMA",
      "BLACK SPIRIT",
      "ACE"
    ],
    "rawTitle": "SCI-FI RIVER, ANIMA, BLACK SPIRIT, ACE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-11-18_sci-fi-river-anima-black-spirit-x-ace.jpg"
  },
  {
    "date": "2023-11-11",
    "bands": [
      "ΔΡΑΜΑ ΚΩΜΙΚΟΥ & THE DRAMOULINS",
      "BABY CULT"
    ],
    "rawTitle": "ΔΡΑΜΑ ΚΩΜΙΚΟΥ & THE DRAMOULINS, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-11-11_dramakomikou-babycult.jpg"
  },
  {
    "date": "2023-11-05",
    "bands": [
      "MOCM",
      "SICKSACK"
    ],
    "rawTitle": "MOCM, SICKSACK",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-11-05_mocm-and-sicksack.jpg"
  },
  {
    "date": "2023-09-23",
    "bands": [
      "LOST BODIES",
      "LOS TRE"
    ],
    "rawTitle": "LOST BODIES, LOS TRE",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2023-2024/2023-09-23_lostbodies_lostre.jpg"
  },
  {
    "date": "2023-07-23",
    "bands": [
      "GREEN WAS GREENER",
      "HUMACHINES"
    ],
    "rawTitle": "GREEN WAS GREENER, HUMACHINES",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-07-23_greenandhumachiens.jpg"
  },
  {
    "date": "2023-06-10",
    "bands": [
      "HEXIS",
      "PS STAMPS BACK"
    ],
    "rawTitle": "HEXIS, PS STAMPS BACK",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-06-10_hexis-ps-stamps-back.jpg"
  },
  {
    "date": "2023-05-27",
    "bands": [
      "KOOBA TERCU",
      "THE BOOMS",
      "MELLOW LIZARD",
      "HEMINGWAYS"
    ],
    "rawTitle": "KOOBA TERCU, THE BOOMS, MELLOW LIZARD, HEMINGWAYS",
    "eventType": "Voutopia Fest",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "stoa60"
    ],
    "poster": "2022-2023/2023-05-27_koobatopia_fest.jpg"
  },
  {
    "date": "2023-05-23",
    "bands": [
      "SAIKO",
      "SMOKA & DEADMIC",
      "ΣΤΙΓΜΑ",
      "BLACK SPIRIT"
    ],
    "rawTitle": "SAIKO, SMOKA & DEADMIC, ΣΤΙΓΜΑ, BLACK SPIRIT",
    "eventType": "Voutopia Fest",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "stoa60"
    ],
    "poster": "2022-2023/2023-05-23_voutopiahiphop_fest.jpg"
  },
  {
    "date": "2023-05-20",
    "bands": [
      "RIO",
      "HUMACHINES"
    ],
    "rawTitle": "RIO, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-05-20_rio-humachines.jpg"
  },
  {
    "date": "2023-05-12",
    "bands": [
      "BAIT",
      "OI BOYS"
    ],
    "rawTitle": "BAIT, OI BOYS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-05-12_bait-oi-boys.jpg"
  },
  {
    "date": "2023-05-06",
    "bands": [
      "DEZO SPAZZ",
      "GROOM IN VINEYARDS & THE LIGHTBENDER",
      "GRIM MACHINE"
    ],
    "rawTitle": "DEZO SPAZZ, GROOM IN VINEYARDS & THE LIGHTBENDER, GRIM MACHINE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-05-06_dezo-spazz-groom-in-vineyards-and-the-lightbender-grim-machine.jpg"
  },
  {
    "date": "2023-05-05",
    "bands": [
      "ANNALIZED",
      "NOIOSE"
    ],
    "rawTitle": "ANNALIZED, NOIOSE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-05-05_annalized-noiose.jpg"
  },
  {
    "date": "2023-04-29",
    "bands": [
      "ΟΡΥΜΑΓΔΟΣ",
      "YAKUZA"
    ],
    "rawTitle": "ΟΡΥΜΑΓΔΟΣ, YAKUZA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-04-29_orymagdos-yakuza.jpg"
  },
  {
    "date": "2023-04-22",
    "bands": [
      "ΑΔΑΕΙΣ",
      "ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ"
    ],
    "rawTitle": "ΑΔΑΕΙΣ, ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-04-22_adaeis-afiloxeno-soma.jpg"
  },
  {
    "date": "2023-04-08",
    "bands": [
      "KOSTADIS",
      "RCRENDER",
      "ECHO CANYON",
      "TURBO TEETH"
    ],
    "rawTitle": "KOSTADIS, RCRENDER, ECHO CANYON, TURBO TEETH",
    "eventType": "Nite Visita",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-04-08_nite-visita-kostadis-rcrender-echo-canyon-turboteeth.jpg"
  },
  {
    "date": "2023-04-01",
    "bands": [
      "CHAIN CULT",
      "THYMICS"
    ],
    "rawTitle": "CHAIN CULT, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-04-01_chain-cult-thymics.jpg"
  },
  {
    "date": "2023-03-25",
    "bands": [
      "KARMAKIND",
      "ΠΑΛΙΑΤΣΟΣ x AEON",
      "ΧΩΡΙΣ ΚΑΝΟΝΑ x MORELLI",
      "KAYHEAL x FAZZA x SAMANOS"
    ],
    "rawTitle": "KARMAKIND, ΠΑΛΙΑΤΣΟΣ x AEON, ΧΩΡΙΣ ΚΑΝΟΝΑ x MORELLI, KAYHEAL x FAZZA x SAMANOS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-03-25_2imero-sordalias.jpg"
  },
  {
    "date": "2023-03-18",
    "bands": [
      "COMMUTER"
    ],
    "rawTitle": "COMMUTER",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-03-18_commuter.jpg"
  },
  {
    "date": "2023-03-11",
    "bands": [
      "ZAKULA",
      "SCARFLOOD"
    ],
    "rawTitle": "ZAKULA, SCARFLOOD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-03-11_zakula-scarflood.jpg"
  },
  {
    "date": "2023-03-04",
    "bands": [
      "NEVER-TRUST",
      "ΕΝΤΕΡΟΝ ΗΜΙΣΥ"
    ],
    "rawTitle": "NEVER-TRUST, ΕΝΤΕΡΟΝ ΗΜΙΣΥ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-03-04_never-trust-enteron-imisy.jpg"
  },
  {
    "date": "2023-02-25",
    "bands": [
      "BAR ΟΙΚΟΝΟΜΙΚΗΣ ΕΝΙΣΧΥΣΗΣ"
    ],
    "rawTitle": "BAR ΟΙΚΟΝΟΜΙΚΗΣ ΕΝΙΣΧΥΣΗΣ",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-02-25_deutero.jpg"
  },
  {
    "date": "2023-02-17",
    "bands": [
      "ΨΑΡΟΓΙΩΡΓΗΣ",
      "ΞΕΦΡΕΝΟ ΑΕΡΟΣΤΑΤΟ"
    ],
    "rawTitle": "ΨΑΡΟΓΙΩΡΓΗΣ, ΞΕΦΡΕΝΟ ΑΕΡΟΣΤΑΤΟ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-02-17_psarogiorgis-xefreno-aerostato.jpg"
  },
  {
    "date": "2023-02-11",
    "bands": [
      "BABY CULT"
    ],
    "rawTitle": "BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-02-11_baby-cult.jpg"
  },
  {
    "date": "2023-02-04",
    "bands": [
      "JUNKWOLVZ",
      "LEGACY"
    ],
    "rawTitle": "JUNKWOLVZ, LEGACY",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-02-04_junkwolvz-legacy.jpg"
  },
  {
    "date": "2023-01-28",
    "bands": [
      "ΦΑΛΚΟΝΕΡΑ",
      "PIRATES CITY"
    ],
    "rawTitle": "ΦΑΛΚΟΝΕΡΑ, PIRATES CITY",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-01-28_falkonera-pirates-city.jpg"
  },
  {
    "date": "2023-01-14",
    "bands": [
      "ΤΟΞΙΚΑ ΑΠΟΒΛΗΤΑ",
      "MANAKULA"
    ],
    "rawTitle": "ΤΟΞΙΚΑ ΑΠΟΒΛΗΤΑ, MANAKULA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2023-01-14_toxika-apovlita-manakula.jpg"
  },
  {
    "date": "2022-12-17",
    "bands": [
      "HAILSTEEL",
      "AXEON"
    ],
    "rawTitle": "HAILSTEEL, AXEON",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-12-17_hailsteel-axeon.jpg"
  },
  {
    "date": "2022-12-09",
    "bands": [
      "ΕΚΤΟΣ ΕΛΕΓΧΟΥ",
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
      "THE FLAT SURFERS"
    ],
    "rawTitle": "ΕΚΤΟΣ ΕΛΕΓΧΟΥ, ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ, THE FLAT SURFERS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-12-09_ektos-elegchoy-otompritsi-motori-the-flat-surfers.jpg"
  },
  {
    "date": "2022-12-03",
    "bands": [
      "NEO TERAS",
      "HUMACHINES"
    ],
    "rawTitle": "NEO TERAS, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-12-03_neo-teras-humachines.jpg"
  },
  {
    "date": "2022-11-26",
    "bands": [
      "BUS THE UNKNOWN SECRETARY"
    ],
    "rawTitle": "BUS THE UNKNOWN SECRETARY",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-11-26_bus-the-unknown-secretary.jpg"
  },
  {
    "date": "2022-11-19",
    "bands": [
      "RAMPAGE!",
      "FRENZEE"
    ],
    "rawTitle": "RAMPAGE!, FRENZEE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-11-19_rampage-frenzee.jpg"
  },
  {
    "date": "2022-11-12",
    "bands": [
      "STYLIANOS OU",
      "OLA VIA",
      "MIZI"
    ],
    "rawTitle": "STYLIANOS OU, OLA VIA, MIZI",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2022-2023/2022-11-12-Ollavia.jpg"
  },
  {
    "date": "2022-11-05",
    "bands": [
      "LAME BEACH",
      "MELLOW LIZARD"
    ],
    "rawTitle": "LAME BEACH, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-11-05_lame-beach-mellow-lizard.jpg"
  },
  {
    "date": "2022-10-21",
    "bands": [
      "DEATH DRIVE",
      "HELHOLTZ"
    ],
    "rawTitle": "DEATH DRIVE, HELHOLTZ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-10-21_death-drive-helholtz__ba2037.jpg"
  },
  {
    "date": "2022-10-15",
    "bands": [
      "GEMMA",
      "TWENTYSEVEN"
    ],
    "rawTitle": "GEMMA, TWENTYSEVEN",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-10-15_gemma-twentyseven.jpg"
  },
  {
    "date": "2022-10-07",
    "bands": [
      "DOUBLE TROUBLE BAR"
    ],
    "rawTitle": "DOUBLE TROUBLE BAR",
    "eventType": "Bar",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-10-07_doubletrouble.jpg"
  },
  {
    "date": "2022-10-01",
    "bands": [
      "DURY DAVA",
      "GREEN WAS GREENER"
    ],
    "rawTitle": "DURY DAVA, GREEN WAS GREENER",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2022-2023/2022-10-01_dury-dava-green-was-greener.jpg"
  },
  {
    "date": "2022-07-16",
    "bands": [
      "PARTY KARAVOLAS"
    ],
    "rawTitle": "PARTY KARAVOLAS",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2022-07-16_party.jpg"
  },
  {
    "date": "2022-07-13",
    "bands": [
      "CENTRAL POZITRONICS",
      "FRENZEE",
      "BABY CULT",
      "KRATS",
      "GEMMA"
    ],
    "rawTitle": "CENTRAL POZITRONICS, FRENZEE, BABY CULT, KRATS, GEMMA",
    "eventType": "Makrovoutes",
    "location": "voutes",
    "organiser": [
      "rastapank"
    ],
    "poster": "2021-2022/2022-07-13-pozitronics_fest.jpg"
  },
  {
    "date": "2022-06-17",
    "bands": [
      "SCREAMING FLY",
      "ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ"
    ],
    "rawTitle": "SCREAMING FLY, ΑΦΙΛΟΞΕΝΟ ΣΩΜΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2022-06-17_screaming_fly_afilokseno.jpg"
  },
  {
    "date": "2022-06-11",
    "bands": [
      "COSMIC SHADOWS",
      "MELLOW LIZARD",
      "PALESTINI2"
    ],
    "rawTitle": "COSMIC SHADOWS, MELLOW LIZARD, PALESTINI2",
    "eventType": "Fertility Fest",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2022-06-11_fertility_black_fest.jpg"
  },
  {
    "date": "2022-05-28",
    "bands": [
      "DRY COUGH",
      "HOUSE OF TOLERANCE"
    ],
    "rawTitle": "DRY COUGH, HOUSE OF TOLERANCE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2022-05-28_DRY COUGH_fb.jpg"
  },
  {
    "date": "2022-04-30",
    "bands": [
      "PROLETKULT RADIO",
      "KICKING NERVE",
      "BABY CULT"
    ],
    "rawTitle": "PROLETKULT RADIO, KICKING NERVE, BABY CULT",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2022-04-30_proletkult.jpg"
  },
  {
    "date": "2021-11-05",
    "bands": [
      "HEKATE",
      "JOJO SAWAVE",
      "HUMACHINES"
    ],
    "rawTitle": "HEKATE, JOJO SAWAVE, HUMACHINES",
    "eventType": "gig",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "ba2037"
    ],
    "poster": "2021-2022/2021-11-05_hekate.jpg"
  },
  {
    "date": "2021-09-25",
    "bands": [
      "MELLOW LIZARD",
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
      "THYMICS"
    ],
    "rawTitle": "MELLOW LIZARD, ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ, THYMICS",
    "eventType": "gig",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "stoa60"
    ],
    "poster": "2021-2022/2021-09-25_mellow_otobritsi_thymics.jpg"
  },
  {
    "date": "2021-09-18",
    "bands": [
      "ΑΔΑΕΙΣ",
      "360"
    ],
    "rawTitle": "ΑΔΑΕΙΣ, 360",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2021-09-18_adaeis.jpg"
  },
  {
    "date": "2021-09-11",
    "bands": [
      "NERRVES",
      "BABY CULT"
    ],
    "rawTitle": "NERRVES, BABY CULT",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2021-2022/2021-09-11_nerves_babycult.jpg"
  },
  {
    "date": "2021-07-24",
    "bands": [
      "CORTES",
      "MARYSHAW",
      "3ΠΔ"
    ],
    "rawTitle": "CORTES, MARYSHAW, 3ΠΔ",
    "eventType": "gig",
    "location": "voutes",
    "organiser": [
      "rastapank"
    ],
    "poster": "2020-2021/2021-07-24-cortes.jpg"
  },
  {
    "date": "2021-05-14",
    "bands": [
      "LOST BODIES",
      "SKLAVOS"
    ],
    "rawTitle": "LOST BODIES, SKLAVOS",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2020-2021/2021-05-14_lost_bodies_sclavos.jpg"
  },
  {
    "date": "2020-07-11",
    "bands": [
      "DRUMACHINE",
      "THYMICS",
      "MELLOW LIZARD"
    ],
    "rawTitle": "DRUMACHINE, THYMICS, MELLOW LIZARD",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-07-11_dramachine.jpg"
  },
  {
    "date": "2020-06-19",
    "bands": [
      "ENETIKA TEIXI SOIRE"
    ],
    "rawTitle": "ENETIKA TEIXI SOIRE",
    "eventType": "Party",
    "location": "walls",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2020-06-19_TEIXI.jpg"
  },
  {
    "date": "2020-03-07",
    "bands": [
      "YELLOW DEVIL SAUCE",
      "OKWAHO"
    ],
    "rawTitle": "YELLOW DEVIL SAUCE, OKWAHO",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-03-07_yellow-devil-sauce-okwaho.jpg"
  },
  {
    "date": "2020-02-29",
    "bands": [
      "NEVER-TRUST",
      "BELOW THE BOTTOM"
    ],
    "rawTitle": "NEVER-TRUST, BELOW THE BOTTOM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-02-29_never-trust-below-the-bottom.jpg"
  },
  {
    "date": "2020-02-15",
    "bands": [
      "GRANDMASTER COCKROACH",
      "MELLOW LIZARD"
    ],
    "rawTitle": "GRANDMASTER COCKROACH, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-02-15_grandmaster-cockroach-mellow-lizard.jpg"
  },
  {
    "date": "2020-02-08",
    "bands": [
      "MOTIFF",
      "BABY CULT"
    ],
    "rawTitle": "MOTIFF, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-02-08_motiff-baby-cult.jpg"
  },
  {
    "date": "2020-02-01",
    "bands": [
      "YOVEL",
      "DEMENTIA"
    ],
    "rawTitle": "YOVEL, DEMENTIA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-02-01_yovel-dementia.jpg"
  },
  {
    "date": "2020-01-26",
    "bands": [
      "THE SEXY CHRISTIANS",
      "THYMICS"
    ],
    "rawTitle": "THE SEXY CHRISTIANS, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-01-26_the-sexy-christians-thymics.jpg"
  },
  {
    "date": "2020-01-25",
    "bands": [
      "LYCURGUS",
      "IMPEDANCE"
    ],
    "rawTitle": "LYCURGUS, IMPEDANCE",
    "eventType": "Saturday Takeover",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2020-01-25_Lycurgus.jpg"
  },
  {
    "date": "2020-01-19",
    "bands": [
      "EAZY",
      "RND ACCESS",
      "MX"
    ],
    "rawTitle": "EAZY, RND ACCESS, MX",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2020-01-19_EAZYRND.jpg"
  },
  {
    "date": "2020-01-18",
    "bands": [
      "BELOW THE BOTTOM",
      "REPRISAL"
    ],
    "rawTitle": "BELOW THE BOTTOM, REPRISAL",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-01-18_below-the-bottom-reprisal_v2.jpg"
  },
  {
    "date": "2020-01-11",
    "bands": [
      "NURSE OF WAR",
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ"
    ],
    "rawTitle": "NURSE OF WAR, ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-01-11_nurse-of-war-otompritsi-motori.jpg"
  },
  {
    "date": "2020-01-04",
    "bands": [
      "TIDAL SHOCK",
      "PRIMO BAKE"
    ],
    "rawTitle": "TIDAL SHOCK, PRIMO BAKE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2020-01-04_tidal-shock-primo-bake.jpg"
  },
  {
    "date": "2019-12-14",
    "bands": [
      "PS STAMPS BACK",
      "MOLFETUS"
    ],
    "rawTitle": "PS STAMPS BACK, MOLFETUS",
    "eventType": "Saturday Takeover",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2019-12-14_MOLFETUS.jpg"
  },
  {
    "date": "2019-12-12",
    "bands": [
      "ΔΡΑΜΑ ΚΩΜΙΚΟΥ",
      "ΑΝΤΙΘΕΤΗ ΦΩΝΗ",
      "ΛΟΓΟΥ ΧΑΡΙΝ",
      "ΣΑΙΚΟ",
      "NYX"
    ],
    "rawTitle": "ΔΡΑΜΑ ΚΩΜΙΚΟΥ, ΑΝΤΙΘΕΤΗ ΦΩΝΗ, ΛΟΓΟΥ ΧΑΡΙΝ, ΣΑΙΚΟ, NYX",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-12-12_drama.jpg"
  },
  {
    "date": "2019-12-01",
    "bands": [
      "HEAD ON",
      "LITTLE VIRGIN EXPERIENCE"
    ],
    "rawTitle": "HEAD ON, LITTLE VIRGIN EXPERIENCE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-01-12_head-on-little-virgin-experience.jpg"
  },
  {
    "date": "2019-11-30",
    "bands": [
      "REVERB SNATCHERS",
      "THE THIN BASTARDS"
    ],
    "rawTitle": "REVERB SNATCHERS, THE THIN BASTARDS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-11-30_reverb-snatchers-the-thin-bastards.jpg"
  },
  {
    "date": "2019-11-24",
    "bands": [
      "ΞΕΦΡΕΝΟ ΑΕΡΟΣΤΑΤΟ"
    ],
    "rawTitle": "ΞΕΦΡΕΝΟ ΑΕΡΟΣΤΑΤΟ",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2019-11-24_xefreno.jpg"
  },
  {
    "date": "2019-11-23",
    "bands": [
      "HAND & LEG",
      "HUMACHINES"
    ],
    "rawTitle": "HAND & LEG, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-11-23_hand-and-leg-humachines.jpg"
  },
  {
    "date": "2019-11-16",
    "bands": [
      "THREE WAY PLANE",
      "BLOCK 16"
    ],
    "rawTitle": "THREE WAY PLANE, BLOCK 16",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-11-16_threewayblock.jpg"
  },
  {
    "date": "2019-11-09",
    "bands": [
      "VISIONS OF WAR",
      "PUNKOFONIX"
    ],
    "rawTitle": "VISIONS OF WAR, PUNKOFONIX",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-11-09_visions-of-war-punkofonix.jpg"
  },
  {
    "date": "2019-11-02",
    "bands": [
      "ANTON BEATBOX",
      "IMPEDANCE"
    ],
    "rawTitle": "ANTON BEATBOX, IMPEDANCE",
    "eventType": "Saturday Takeover",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2019-11-02_TAKEOVER1.jpg"
  },
  {
    "date": "2019-10-26",
    "bands": [
      "THYMICS",
      "MELLOW LIZARD"
    ],
    "rawTitle": "THYMICS, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-10-26_thymics-mellow-lizard_fb.jpg"
  },
  {
    "date": "2019-10-19",
    "bands": [
      "EMBRACE OF THORNS",
      "SLAUGHTERED PRIEST",
      "YOVEL"
    ],
    "rawTitle": "EMBRACE OF THORNS, SLAUGHTERED PRIEST, YOVEL",
    "eventType": "Underworld Rises",
    "location": "underground",
    "organiser": [
      "stoa60",
      "vomvos"
    ],
    "poster": "2019-2020/2019-10-19_underworld-rises-festival-vii-embrace-of-thorns-slaughtered-priest-yovel.jpg"
  },
  {
    "date": "2019-10-12",
    "bands": [
      "BAZOOKA",
      "GAY ANNIVERSARY"
    ],
    "rawTitle": "BAZOOKA, GAY ANNIVERSARY",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-10-12_bazooka-gay-anniversary.jpg"
  },
  {
    "date": "2019-10-05",
    "bands": [
      "THE BOOMS"
    ],
    "rawTitle": "THE BOOMS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-10-05_the-booms.jpg"
  },
  {
    "date": "2019-09-28",
    "bands": [
      "SITARSONIC",
      "BJORN ALPHA"
    ],
    "rawTitle": "SITARSONIC, BJORN ALPHA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-09-28_sitarsonic-bjorn-alpha.jpg"
  },
  {
    "date": "2019-09-20",
    "bands": [
      "KOHU 63",
      "THE THIN BASTARDS"
    ],
    "rawTitle": "KOHU 63, THE THIN BASTARDS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-09-20_kohu-63-the-thin-bastards_fb.jpg"
  },
  {
    "date": "2019-09-14",
    "bands": [
      "BUS",
      "OKWAHO",
      "THYMICS",
      "TIDAL SHOCK",
      "HASHIYA"
    ],
    "rawTitle": "BUS, OKWAHO, THYMICS, TIDAL SHOCK, HASHIYA",
    "eventType": "Down Tuned Dazed",
    "location": "karabolas",
    "organiser": [
      "stoa60",
      "vomvos"
    ],
    "poster": "2019-2020/2019-09-14_downtuneddaze_fest.jpg"
  },
  {
    "date": "2019-09-07",
    "bands": [
      "PARTY STOA 60"
    ],
    "rawTitle": "PARTY STOA 60",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2019-2020/2019-09-07_party-stoa60.jpg"
  },
  {
    "date": "2019-08-31",
    "bands": [
      "PARTY BA2037"
    ],
    "rawTitle": "PARTY BA2037",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-08-31_karavolas.jpg"
  },
  {
    "date": "2019-07-13",
    "bands": [
      "ΝΟΜΟΣ 751",
      "$OFT $KULL",
      "KOONOOPOMANA",
      "DURY DAVA",
      "GRIN"
    ],
    "rawTitle": "ΝΟΜΟΣ 751, $OFT $KULL, KOONOOPOMANA, DURY DAVA, GRIN",
    "eventType": "Tsurai Fest",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-07-13_tsurai2_fest.jpg"
  },
  {
    "date": "2019-06-15",
    "bands": [
      "THYMICS",
      "MELLOW LIZARD",
      "QUEEN TAKES JACK",
      "HUMACHINES"
    ],
    "rawTitle": "THYMICS, MELLOW LIZARD, QUEEN TAKES JACK, HUMACHINES",
    "eventType": "Fertility Fest",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-06-15-dayoffertility.jpg"
  },
  {
    "date": "2019-05-25",
    "bands": [
      "MAZOHA",
      "BLAKAUT"
    ],
    "rawTitle": "MAZOHA, BLAKAUT",
    "eventType": "gig",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-05-25_mazoha-blakaut.jpg"
  },
  {
    "date": "2019-05-18",
    "bands": [
      "VENUS VOLCANISM IN ATLAS",
      "KRATS",
      "FETA NAGASAKI"
    ],
    "rawTitle": "VENUS VOLCANISM IN ATLAS, KRATS, FETA NAGASAKI",
    "eventType": "Makrovoutes",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "ba2037"
    ],
    "poster": "2018-2019/2019-05-18_makro.jpg"
  },
  {
    "date": "2019-05-16",
    "bands": [
      "TIDAL SHOCK",
      "THYMICS",
      "GRIN",
      "BABY CULT"
    ],
    "rawTitle": "TIDAL SHOCK, THYMICS, GRIN, BABY CULT",
    "eventType": "Makrovoutes",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "stoa60"
    ],
    "poster": "2018-2019/2019-05-16-makrovoutes_fest.jpg"
  },
  {
    "date": "2019-05-11",
    "bands": [
      "ΑΓΟΡΙΑΣΤΟΝΗΛΙΟ"
    ],
    "rawTitle": "ΑΓΟΡΙΑΣΤΟΝΗΛΙΟ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-05-11_agoriastonilio.jpg"
  },
  {
    "date": "2019-05-04",
    "bands": [
      "PARTY"
    ],
    "rawTitle": "PARTY",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-05-04_party.jpg"
  },
  {
    "date": "2019-04-14",
    "bands": [
      "KOSTADIS",
      "TURBO TEETH"
    ],
    "rawTitle": "KOSTADIS, TURBO TEETH",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2018-2019/2019-04-14_kostadis.jpg"
  },
  {
    "date": "2019-04-08",
    "bands": [
      "MONOVINE",
      "THYMICS"
    ],
    "rawTitle": "MONOVINE, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-04-08_monovine-thymics.jpg"
  },
  {
    "date": "2019-04-04",
    "bands": [
      "MR. CLARINET"
    ],
    "rawTitle": "MR. CLARINET",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-04-04_mr-clarinet.jpg"
  },
  {
    "date": "2019-03-31",
    "bands": [
      "LAST DAYS OF SEX",
      "SOLAR ANUS",
      "KRATS"
    ],
    "rawTitle": "LAST DAYS OF SEX, SOLAR ANUS, KRATS",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2018-2019/2019-03-31_Lastdays.jpg"
  },
  {
    "date": "2019-03-30",
    "bands": [
      "100TH ANNIVERSARY",
      "MELLOW LIZARD",
      "SKUMA",
      "GRIN",
      "HUMACHINES"
    ],
    "rawTitle": "100TH ANNIVERSARY, MELLOW LIZARD, SKUMA, GRIN, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-03-30_100th-anniversary-mellow-lizard-skuma-grin-humachines.jpg"
  },
  {
    "date": "2019-03-23",
    "bands": [
      "LITTLE VIRGIN EXPERIENCE",
      "MERIDIAN BLANK"
    ],
    "rawTitle": "LITTLE VIRGIN EXPERIENCE, MERIDIAN BLANK",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-03-23_little-virgin-experience-meridian-blank.jpg"
  },
  {
    "date": "2019-03-19",
    "bands": [
      "WEEDWOLF",
      "TIDAL SHOCK"
    ],
    "rawTitle": "WEEDWOLF, TIDAL SHOCK",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-03-19_weedwolf-tidal-shock.jpg"
  },
  {
    "date": "2019-03-16",
    "bands": [
      "REPRISAL",
      "PURE VIOLENT HEDONISM"
    ],
    "rawTitle": "REPRISAL, PURE VIOLENT HEDONISM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-03-16_reprisalpvhedonism.jpg"
  },
  {
    "date": "2019-03-09",
    "bands": [
      "SANS CORPS"
    ],
    "rawTitle": "SANS CORPS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-03-09_sans-corps.jpg"
  },
  {
    "date": "2019-03-02",
    "bands": [
      "DUOYU",
      "SUGAR KANE"
    ],
    "rawTitle": "DUOYU, SUGAR KANE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-03-02_duoyu-sugar-kane.jpg"
  },
  {
    "date": "2019-02-24",
    "bands": [
      "ANFS"
    ],
    "rawTitle": "ANFS",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2018-2019/2019-02-24_ANFS.jpg"
  },
  {
    "date": "2019-02-23",
    "bands": [
      "INFLUENZA",
      "BABY CULT"
    ],
    "rawTitle": "INFLUENZA, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-02-23_influenza-baby-cult.jpg"
  },
  {
    "date": "2019-02-16",
    "bands": [
      "MISSBRAUCH",
      "THE THIN BASTARDS"
    ],
    "rawTitle": "MISSBRAUCH, THE THIN BASTARDS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-02-16_missbrauch-the-thin-bastards.jpg"
  },
  {
    "date": "2019-02-10",
    "bands": [
      "DELEVELED"
    ],
    "rawTitle": "DELEVELED",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2018-2019/2019-02-10_deleveled.jpg"
  },
  {
    "date": "2019-02-09",
    "bands": [
      "COSMIC PLUNGE",
      "WISE ASTRONOMIST"
    ],
    "rawTitle": "COSMIC PLUNGE, WISE ASTRONOMIST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-02-09_cosmic-plunge-wise-astronomist.jpg"
  },
  {
    "date": "2019-02-02",
    "bands": [
      "AUTOMATON",
      "TIDAL SHOCK"
    ],
    "rawTitle": "AUTOMATON, TIDAL SHOCK",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-02-02_automaton-tidal-shock.jpg"
  },
  {
    "date": "2019-01-26",
    "bands": [
      "SWIM TO CAPE SHERPA",
      "BERDNTURTLE"
    ],
    "rawTitle": "SWIM TO CAPE SHERPA, BERDNTURTLE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-01-26_swim-to-cape-sherpa-berdnturtle.jpg"
  },
  {
    "date": "2019-01-19",
    "bands": [
      "PSYCHEDELIC TRIPS TO DEATH",
      "HUMACHINES"
    ],
    "rawTitle": "PSYCHEDELIC TRIPS TO DEATH, HUMACHINES",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2019-01-19_Psychedelictrips.jpg"
  },
  {
    "date": "2019-01-13",
    "bands": [
      "DEEP IN MIND"
    ],
    "rawTitle": "DEEP IN MIND",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2018-2019/2019-01-13_secondsunday.jpg"
  },
  {
    "date": "2019-01-12",
    "bands": [
      "TONTO",
      "KRATS"
    ],
    "rawTitle": "TONTO, KRATS",
    "eventType": "gig",
    "location": "evangelismos",
    "organiser": [
      "ba2037"
    ],
    "poster": "2019-2020/2019-12-01_tonto.jpg"
  },
  {
    "date": "2018-12-29",
    "bands": [
      "CRISIS CALL",
      "TERRIE"
    ],
    "rawTitle": "CRISIS CALL, TERRIE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-12-29_crisis-call-terrie.jpg"
  },
  {
    "date": "2018-12-22",
    "bands": [
      "NYX",
      "BLACK SPIRIT X ACE",
      "ΜΥΣΤΗΡΙΟΣ ΤΥΠΟΣ",
      "SKALE"
    ],
    "rawTitle": "NYX, BLACK SPIRIT X ACE, ΜΥΣΤΗΡΙΟΣ ΤΥΠΟΣ, SKALE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-12-22_nyx-black-spirit-x-ace-mystirios-typos-skale.jpg"
  },
  {
    "date": "2018-12-21",
    "bands": [
      "ΒΟΥΤΕΣ ΠΑΡΤΥ"
    ],
    "rawTitle": "ΒΟΥΤΕΣ ΠΑΡΤΥ",
    "eventType": "Party",
    "location": "voutes",
    "organiser": [
      "rastapank",
      "ba2037"
    ],
    "poster": "2018-2019/2018-12-21_voutesparty.jpg"
  },
  {
    "date": "2018-12-14",
    "bands": [
      "NERRVES",
      "MELLON SNACKMAN IGUANA"
    ],
    "rawTitle": "NERRVES, MELLON SNACKMAN IGUANA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-12-14_nerrves-mellon-snackman-iguana.jpg"
  },
  {
    "date": "2018-12-08",
    "bands": [
      "TREEP",
      "THYMICS"
    ],
    "rawTitle": "TREEP, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-12-08_treep-thymics.jpg"
  },
  {
    "date": "2018-12-02",
    "bands": [
      "SILENCE OF THE GOAT",
      "MX"
    ],
    "rawTitle": "SILENCE OF THE GOAT, MX",
    "eventType": "Experimental Sundays",
    "location": "underground",
    "organiser": [
      "ba2037"
    ],
    "poster": "2018-2019/2018-12-02_firstSunday.jpg"
  },
  {
    "date": "2018-12-01",
    "bands": [
      "BLACK SUMMER",
      "PUNKOFONIX",
      "ΣΤΡΑΦΙ"
    ],
    "rawTitle": "BLACK SUMMER, PUNKOFONIX, ΣΤΡΑΦΙ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-12-01_black-summer-punkofonix-strafi.jpg"
  },
  {
    "date": "2018-11-10",
    "bands": [
      "TWINSANITY",
      "AFEZZ",
      "ΣΑΙΚΟ",
      "MISS ZEBRA"
    ],
    "rawTitle": "TWINSANITY, AFEZZ, ΣΑΙΚΟ, MISS ZEBRA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-11-10_twinsanity-afezz-saiko-miss-zebra.jpg"
  },
  {
    "date": "2018-11-02",
    "bands": [
      "MARK MORGAN",
      "DEAD GUM"
    ],
    "rawTitle": "MARK MORGAN, DEAD GUM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-11-02_mark-morgan-dead-gum.jpg"
  },
  {
    "date": "2018-10-27",
    "bands": [
      "MELLOW LIZARD",
      "ΜΙΝΕΡΒΑ"
    ],
    "rawTitle": "MELLOW LIZARD, ΜΙΝΕΡΒΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-10-27_mellow-lizard-minerva.jpg"
  },
  {
    "date": "2018-10-24",
    "bands": [
      "INSECT RADIO",
      "BELOW THE BOTTOM"
    ],
    "rawTitle": "INSECT RADIO, BELOW THE BOTTOM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-10-24_insect-radio-below-the-bottom.jpg"
  },
  {
    "date": "2018-10-17",
    "bands": [
      "RITA MOSS",
      "IONLYSLEEPWITHTHEBEST"
    ],
    "rawTitle": "RITA MOSS, IONLYSLEEPWITHTHEBEST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-10-17_rita-moss-ionlysleepwiththebest.jpg"
  },
  {
    "date": "2018-10-14",
    "bands": [
      "TWO HORSES AND A COW"
    ],
    "rawTitle": "TWO HORSES AND A COW",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-10-14_two-horses-and-a-cow.jpg"
  },
  {
    "date": "2018-10-06",
    "bands": [
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
      "ΑΧΑΙΡΕΥΤΟΙ"
    ],
    "rawTitle": "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ, ΑΧΑΙΡΕΥΤΟΙ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-10-06_otompritsi-motori-achaireytoi.jpg"
  },
  {
    "date": "2018-09-08",
    "bands": [
      "1000MODS"
    ],
    "rawTitle": "1000MODS",
    "eventType": "Down Tuned Dazed",
    "location": "georgiadis",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-09-08_1000MODS_fest.jpg"
  },
  {
    "date": "2018-09-01",
    "bands": [
      "PARTY SIMULATION EXPERIMENT"
    ],
    "rawTitle": "PARTY SIMULATION EXPERIMENT",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2018-2019/2018-09-01_experiment.jpg"
  },
  {
    "date": "2018-08-08",
    "bands": [
      "PIRATES CITY"
    ],
    "rawTitle": "PIRATES CITY",
    "eventType": "Party",
    "location": "georgiadis",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-08-08_pirateCity.jpg"
  },
  {
    "date": "2018-07-14",
    "bands": [
      "KOOBA TERCU",
      "WHAM JA",
      "THE PERIODS",
      "ΟΡΗ",
      "MELLON SNACKMAN IGUANA"
    ],
    "rawTitle": "KOOBA TERCU, WHAM JA, THE PERIODS, ΟΡΗ, MELLON SNACKMAN IGUANA",
    "eventType": "Tsurai Fest",
    "location": "georgiadis",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-07-14_first_tsurai_fest.jpg"
  },
  {
    "date": "2018-05-25",
    "bands": [
      "OLA VIA",
      "IMPEDANCE",
      "CHRYSANTHEMUM",
      "OUROBOROS"
    ],
    "rawTitle": "OLA VIA, IMPEDANCE, CHRYSANTHEMUM, OUROBOROS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-05-25_olla-via-impedance-chrysanthemum-ouroboros.jpg"
  },
  {
    "date": "2018-05-19",
    "bands": [
      "PARTY 3 ΧΡΟΝΙΑ ΣΤΟΑ"
    ],
    "rawTitle": "PARTY 3 ΧΡΟΝΙΑ ΣΤΟΑ",
    "eventType": "Party",
    "location": "karabolas",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-05-19_first_karavolas.jpg"
  },
  {
    "date": "2018-05-18",
    "bands": [
      "TWO HORSES AND A COW"
    ],
    "rawTitle": "TWO HORSES AND A COW",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-05-18_two-horses-and-a-cow.jpg"
  },
  {
    "date": "2018-05-05",
    "bands": [
      "SPYRAL OF SILENCE",
      "WISE ASTRONOMIST"
    ],
    "rawTitle": "SPYRAL OF SILENCE, WISE ASTRONOMIST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-05-05_spyral-of-silence-wise-astronomist.jpg"
  },
  {
    "date": "2018-04-27",
    "bands": [
      "ΑΓΟΡΙΑΣΤΟΝΗΛΙΟ",
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ"
    ],
    "rawTitle": "ΑΓΟΡΙΑΣΤΟΝΗΛΙΟ, ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-04-27_agoriastonilio-otobritsi-motori.jpg"
  },
  {
    "date": "2018-04-21",
    "bands": [
      "BEYOND PERCEPTION",
      "O.Y.D"
    ],
    "rawTitle": "BEYOND PERCEPTION, O.Y.D",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-04-21_beyond-perception-oyd.jpg"
  },
  {
    "date": "2018-04-14",
    "bands": [
      "THE CYCLOTHYMICS",
      "THYMICS"
    ],
    "rawTitle": "THE CYCLOTHYMICS, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-04-14_the-cyclothymics-thymics.jpg"
  },
  {
    "date": "2018-03-31",
    "bands": [
      "BLAME KADINSKY",
      "REPRISAL"
    ],
    "rawTitle": "BLAME KADINSKY, REPRISAL",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-03-31_blame-kadinsky-reprisal.jpg"
  },
  {
    "date": "2018-03-24",
    "bands": [
      "CHAIN CULT",
      "TIFFANY"
    ],
    "rawTitle": "CHAIN CULT, TIFFANY",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-03-24_chain-cult-tiffany.jpg"
  },
  {
    "date": "2018-03-17",
    "bands": [
      "ALIEN MUSTANGS",
      "MELLOW LIZARD",
      "MELLON SNACKMAN IGUANA"
    ],
    "rawTitle": "ALIEN MUSTANGS, MELLOW LIZARD, MELLON SNACKMAN IGUANA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-03-17_alien-mustangs-mellow-lizard-mellon-snackman-inguana.jpg"
  },
  {
    "date": "2018-03-10",
    "bands": [
      "CRISIS CALL",
      "PURE VIOLENT HEDONISM"
    ],
    "rawTitle": "CRISIS CALL, PURE VIOLENT HEDONISM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-03-10_pureviolenthedonism.jpg"
  },
  {
    "date": "2018-03-09",
    "bands": [
      "VENUS VOLCANISM",
      "IN ATLAS",
      "IMPEDANCE"
    ],
    "rawTitle": "VENUS VOLCANISM, IN ATLAS, IMPEDANCE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-03-09_venus-volcanism-in-atlas-impedance.jpg"
  },
  {
    "date": "2018-03-03",
    "bands": [
      "ALLOCHIRIA",
      "HASHIYA"
    ],
    "rawTitle": "ALLOCHIRIA, HASHIYA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-03-03_allochiria-hashiya.jpg"
  },
  {
    "date": "2018-02-24",
    "bands": [
      "NEEDSPACE",
      "THYMICS"
    ],
    "rawTitle": "NEEDSPACE, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-02-24_needspace-thymics.jpg"
  },
  {
    "date": "2018-02-17",
    "bands": [
      "DOLLARS FOR DEADBEATS",
      "ΝΤΕΡΤΙ DANCING"
    ],
    "rawTitle": "DOLLARS FOR DEADBEATS, ΝΤΕΡΤΙ DANCING",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-02-17_dollars-for-deadbeats-nterti-dancing.jpg"
  },
  {
    "date": "2018-02-17",
    "bands": [
      "SARABANTE",
      "BUCHANNONS",
      "THIN BASTARDS",
      "OTOΜΠΡΙΤΣΙ ΜΟΤΟΡΙ"
    ],
    "rawTitle": "SARABANTE, BUCHANNONS, THIN BASTARDS, OTOΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
    "eventType": "gig",
    "location": "voutes",
    "organiser": [
      "stoa60",
      "tameiosolidarity"
    ],
    "poster": "2017-2018/2018-02-17_tameio.jpg"
  },
  {
    "date": "2018-02-10",
    "bands": [
      "PUNKOFONIX",
      "BABY CULT"
    ],
    "rawTitle": "PUNKOFONIX, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-02-10_punkofonix-baby-cult.jpg"
  },
  {
    "date": "2018-02-03",
    "bands": [
      "TURBO TEETH",
      "TOKENO",
      "ECHO CANYON"
    ],
    "rawTitle": "TURBO TEETH, TOKENO, ECHO CANYON",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-02-03_turbo-teeth-tokeno-echo-canyon.jpg"
  },
  {
    "date": "2018-01-27",
    "bands": [
      "KRAAK",
      "ΑΔΑΕΙΣ"
    ],
    "rawTitle": "KRAAK, ΑΔΑΕΙΣ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-01-27_kraak-adaeis.jpg"
  },
  {
    "date": "2018-01-20",
    "bands": [
      "LOST BODIES",
      "PROJECT MK ULTRA"
    ],
    "rawTitle": "LOST BODIES, PROJECT MK ULTRA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-01-20_lost-bodies-project-mk-ultra.jpg"
  },
  {
    "date": "2018-01-13",
    "bands": [
      "PULSE",
      "QUEEN TAKES JACK"
    ],
    "rawTitle": "PULSE, QUEEN TAKES JACK",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2018-01-13_pulse-queen-takes-jack.jpg"
  },
  {
    "date": "2017-12-23",
    "bands": [
      "VFD",
      "MISS ZEBRA x DIDI",
      "DEEP x GAN",
      "AEON x RAY",
      "WONE",
      "FLU"
    ],
    "rawTitle": "VFD, MISS ZEBRA x DIDI, DEEP x GAN, AEON x RAY, WONE, FLU",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-12-23_vfd-miss-zebra-x-didi-deep-and-gan-aeon-and-ray-wone-flu.jpg"
  },
  {
    "date": "2017-12-09",
    "bands": [
      "MINERVA SUPERDUTY",
      "REPRISAL"
    ],
    "rawTitle": "MINERVA SUPERDUTY, REPRISAL",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-12-09_minerva-superduty-reprisal.jpg"
  },
  {
    "date": "2017-11-25",
    "bands": [
      "PLAYGROUNDED",
      "ΣΟΦΙΑ ΣΑΡΡΗ"
    ],
    "rawTitle": "PLAYGROUNDED, ΣΟΦΙΑ ΣΑΡΡΗ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-11-25_playground-sofia-sarri.jpg"
  },
  {
    "date": "2017-11-17",
    "bands": [
      "THEIR METHLAB",
      "SWIM TO CAPE SHERPA"
    ],
    "rawTitle": "THEIR METHLAB, SWIM TO CAPE SHERPA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-11-17_their-methlab-swim-to-cape-sherpa.jpg"
  },
  {
    "date": "2017-11-11",
    "bands": [
      "ΗΞΧ",
      "FILM JACKET 35"
    ],
    "rawTitle": "ΗΞΧ, FILM JACKET 35",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-11-11_ixch-film-jacket-35.jpg"
  },
  {
    "date": "2017-11-04",
    "bands": [
      "LITTLE VIRGIN EXPERIENCE",
      "BABY CULT"
    ],
    "rawTitle": "LITTLE VIRGIN EXPERIENCE, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-11-04_little-virgin-experience-baby-cult.jpg"
  },
  {
    "date": "2017-10-28",
    "bands": [
      "SOCIAL WASTE"
    ],
    "rawTitle": "SOCIAL WASTE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-10-28_social-waste.jpg"
  },
  {
    "date": "2017-10-21",
    "bands": [
      "GEMMA",
      "TWO HORSES AND A COW"
    ],
    "rawTitle": "GEMMA, TWO HORSES AND A COW",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-10-21_gemma-two-horses-and-a-cow.jpg"
  },
  {
    "date": "2017-10-14",
    "bands": [
      "OBZERV",
      "MELOW THE BOTTOM"
    ],
    "rawTitle": "OBZERV, MELOW THE BOTTOM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-10-14_obzerv-melow-the-bottom.jpg"
  },
  {
    "date": "2017-10-08",
    "bands": [
      "JOHNNY CARBONARAS"
    ],
    "rawTitle": "JOHNNY CARBONARAS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-10-08_johnny-carbonaras.jpg"
  },
  {
    "date": "2017-10-06",
    "bands": [
      "MY TURN",
      "THE THIN BASTARDS"
    ],
    "rawTitle": "MY TURN, THE THIN BASTARDS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-10-06_my-turn-the-thin-bastards.jpg"
  },
  {
    "date": "2017-09-30",
    "bands": [
      "LAST RIZZLA",
      "AGNES VEIN"
    ],
    "rawTitle": "LAST RIZZLA, AGNES VEIN",
    "eventType": "Down Tuned Dazed",
    "location": "georgiadis",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-09-30_DOWNTUNEDDAZED_fest.jpg"
  },
  {
    "date": "2017-09-16",
    "bands": [
      "ΠΑΡ'ΤΗ PARTY"
    ],
    "rawTitle": "ΠΑΡ'ΤΗ PARTY",
    "eventType": "Party",
    "location": "xenia",
    "organiser": [
      "stoa60"
    ],
    "poster": "2017-2018/2017-09-16_Parth.jpg"
  },
  {
    "date": "2017-05-12",
    "bands": [
      "2 ΧΡΟΝΙΑ ΣΤΟΑ60"
    ],
    "rawTitle": "2 ΧΡΟΝΙΑ ΣΤΟΑ60",
    "eventType": "Party",
    "location": "xenia",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-05-12_2yearsStoa.jpg"
  },
  {
    "date": "2017-05-06",
    "bands": [
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
      "THYMICS",
      "THE THIN BASTARDS",
      "SORDEM"
    ],
    "rawTitle": "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ, THYMICS, THE THIN BASTARDS, SORDEM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-05-06_otobritsi-motori-thymics-the-thin-bastards-sordem.jpg"
  },
  {
    "date": "2017-04-29",
    "bands": [
      "DEATH GRIVE",
      "GROOM IN VINEYARDS",
      "IMPEDANCE"
    ],
    "rawTitle": "DEATH GRIVE, GROOM IN VINEYARDS, IMPEDANCE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-04-29_death-grive-groom-in-vineyards-impedance.jpg"
  },
  {
    "date": "2017-04-22",
    "bands": [
      "CONSPIRACY OF DENIAL",
      "BELOW THE BOTTOM"
    ],
    "rawTitle": "CONSPIRACY OF DENIAL, BELOW THE BOTTOM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-04-22_conspiracy-of-denial-below-the-bottom.jpg"
  },
  {
    "date": "2017-04-07",
    "bands": [
      "KALPA",
      "PURE VIOLENT HEDONISM"
    ],
    "rawTitle": "KALPA, PURE VIOLENT HEDONISM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-04-07_kalpa-pure-violent-hedonism.jpg"
  },
  {
    "date": "2017-04-01",
    "bands": [
      "COSMIC PLUNGE",
      "WISE ASTRONOMIST"
    ],
    "rawTitle": "COSMIC PLUNGE, WISE ASTRONOMIST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-04-01_cosmic-plunge-wise-astronomist.jpg"
  },
  {
    "date": "2017-03-25",
    "bands": [
      "WISH UPON A STAR",
      "PUNKOFONIX"
    ],
    "rawTitle": "WISH UPON A STAR, PUNKOFONIX",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-03-25_wish-upon-a-star-punkofonix.jpg"
  },
  {
    "date": "2017-03-18",
    "bands": [
      "SHATTERED HOPE",
      "OMEGA MONOLITH"
    ],
    "rawTitle": "SHATTERED HOPE, OMEGA MONOLITH",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-03-18_shattered-hope-omega-monolith.jpg"
  },
  {
    "date": "2017-03-11",
    "bands": [
      "RAW NOISE APES",
      "NOMA",
      "ΜΕΛΑΙΝΑ ΧΟΛΗ"
    ],
    "rawTitle": "RAW NOISE APES, NOMA, ΜΕΛΑΙΝΑ ΧΟΛΗ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-03-11_raw-noise-apes-noma-melaina-choli.jpg"
  },
  {
    "date": "2017-03-04",
    "bands": [
      "JOHNNY CARBONARAS",
      "ΦΟΥΝΤΟΥΚΙΑ"
    ],
    "rawTitle": "JOHNNY CARBONARAS, ΦΟΥΝΤΟΥΚΙΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-03-04_johnny-carbonaras-fountoukia.jpg"
  },
  {
    "date": "2017-02-24",
    "bands": [
      "BABEL TRIO",
      "FELIMORMIA"
    ],
    "rawTitle": "BABEL TRIO, FELIMORMIA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-02-24_babel-trio-felimormia.jpg"
  },
  {
    "date": "2017-02-11",
    "bands": [
      "LITTLE VIRGIN EXPERIENCE",
      "BABY CULT"
    ],
    "rawTitle": "LITTLE VIRGIN EXPERIENCE, BABY CULT",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-02-11_little-virgin-experience-baby-cult.jpg"
  },
  {
    "date": "2017-02-04",
    "bands": [
      "MILLIONS OF DEAD TOURISTS",
      "PS STAMPS BACK",
      "ΞΕΡΑ"
    ],
    "rawTitle": "MILLIONS OF DEAD TOURISTS, PS STAMPS BACK, ΞΕΡΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-02-04_millions-of-dead-tourists-ps-stamps-back-xera.jpg"
  },
  {
    "date": "2017-01-28",
    "bands": [
      "MONK",
      "SKUMA"
    ],
    "rawTitle": "MONK, SKUMA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-01-28_monk-skuma.jpg"
  },
  {
    "date": "2017-01-21",
    "bands": [
      "CIRCASSIAN",
      "SWIM TO CAPE SHERPA"
    ],
    "rawTitle": "CIRCASSIAN, SWIM TO CAPE SHERPA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-01-21_circassian-swim-to-cape-sherpa.jpg"
  },
  {
    "date": "2017-01-14",
    "bands": [
      "RAMDAT",
      "ΞΕΦΡΕΝΟ ΑΕΡΟΣΤΑΤΟ"
    ],
    "rawTitle": "RAMDAT, ΞΕΦΡΕΝΟ ΑΕΡΟΣΤΑΤΟ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-01-14_ramdat-xefreno-aerostato.jpg"
  },
  {
    "date": "2017-01-07",
    "bands": [
      "THE ART OF RAW RECORDS",
      "FER DE LANCE"
    ],
    "rawTitle": "THE ART OF RAW RECORDS, FER DE LANCE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2017-01-07_the-art-of-raw-records-and-fer-de-lance.jpg"
  },
  {
    "date": "2016-12-17",
    "bands": [
      "THE STEAMS",
      "MELLOW LIZARD"
    ],
    "rawTitle": "THE STEAMS, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-12-17_the-steams-mellow-lizard.jpg"
  },
  {
    "date": "2016-12-10",
    "bands": [
      "REPRISAL",
      "SARABANTE"
    ],
    "rawTitle": "REPRISAL, SARABANTE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-12-10_reprisal-sarabante.jpg"
  },
  {
    "date": "2016-11-26",
    "bands": [
      "PUNKOFONIX",
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
      "ΑΔΑΕΙΣ"
    ],
    "rawTitle": "PUNKOFONIX, ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ, ΑΔΑΕΙΣ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-11-26_punkofonix-otobritsi-motori-adaeis.jpg"
  },
  {
    "date": "2016-11-19",
    "bands": [
      "CRAANG",
      "MANDA RAY"
    ],
    "rawTitle": "CRAANG, MANDA RAY",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-11-19_craang-and-manda-ray.jpg"
  },
  {
    "date": "2016-11-05",
    "bands": [
      "BELOW THE BOTTOM",
      "NEVER-TRUST"
    ],
    "rawTitle": "BELOW THE BOTTOM, NEVER-TRUST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-11-05_below-the-bottom-never-trust_v2.jpg"
  },
  {
    "date": "2016-10-29",
    "bands": [
      "HAND & LEG",
      "THYMICS"
    ],
    "rawTitle": "HAND & LEG, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-10-29_hand-and-leg-thymics.jpg"
  },
  {
    "date": "2016-10-22",
    "bands": [
      "VOID DROID",
      "WISE ASTRONOMIST"
    ],
    "rawTitle": "VOID DROID, WISE ASTRONOMIST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-10-22_void-droid-wise-astronomist.jpg"
  },
  {
    "date": "2016-10-15",
    "bands": [
      "FILM JACKET 35",
      "THE THIN BASTARDS"
    ],
    "rawTitle": "FILM JACKET 35, THE THIN BASTARDS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-10-15_film-jacket-35-the-thin-bastards.jpg"
  },
  {
    "date": "2016-10-05",
    "bands": [
      "FOX DEVILS WILD",
      "ΝΤΕΡΤΙ DANCING"
    ],
    "rawTitle": "FOX DEVILS WILD, ΝΤΕΡΤΙ DANCING",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-10-05_fox-devils-wild-dirty-dancing.jpg"
  },
  {
    "date": "2016-09-10",
    "bands": [
      "PARTY ΞΕΝΙΑ"
    ],
    "rawTitle": "PARTY ΞΕΝΙΑ",
    "eventType": "Party",
    "location": "xenia",
    "organiser": [
      "stoa60"
    ],
    "poster": "2016-2017/2016-09-10_SecondXenia.jpg"
  },
  {
    "date": "2016-06-18",
    "bands": [
      "PARTY ΞΕΝΙΑ"
    ],
    "rawTitle": "PARTY ΞΕΝΙΑ",
    "eventType": "Party",
    "location": "xenia",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-06-18_firstXenia.jpg"
  },
  {
    "date": "2016-05-13",
    "bands": [
      "BURN THE SUN",
      "WISE ASTRONOMIST"
    ],
    "rawTitle": "BURN THE SUN, WISE ASTRONOMIST",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-05-13_burn-the-sun-wise-astronomist.jpg"
  },
  {
    "date": "2016-05-07",
    "bands": [
      "MISS ZEBRA",
      "ΛΑΘΟΣ ΕΠΟΧΗ",
      "ΠΡΟΠΑΤΩΡ"
    ],
    "rawTitle": "MISS ZEBRA, ΛΑΘΟΣ ΕΠΟΧΗ, ΠΡΟΠΑΤΩΡ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-05-07_miss-zebra-lathos-epochi-propator.jpg"
  },
  {
    "date": "2016-04-23",
    "bands": [
      "THE KANGOORS",
      "LOLLIPOP"
    ],
    "rawTitle": "THE KANGOORS, LOLLIPOP",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-04-23_the-kangoors-lollipop.jpg"
  },
  {
    "date": "2016-04-09",
    "bands": [
      "KAMIKAZI",
      "ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ"
    ],
    "rawTitle": "KAMIKAZI, ΟΤΟΜΠΡΙΤΣΙ ΜΟΤΟΡΙ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-04-09_kamikazi-otobritsi-motori.jpg"
  },
  {
    "date": "2016-04-03",
    "bands": [
      "WHAM JAH",
      "KOSTADIS",
      "DEAD GUM"
    ],
    "rawTitle": "WHAM JAH, KOSTADIS, DEAD GUM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-04-03_corpses-cosmic-plunge_v2.jpg"
  },
  {
    "date": "2016-03-26",
    "bands": [
      "PROCRASTINATE",
      "OUTREIGN"
    ],
    "rawTitle": "PROCRASTINATE, OUTREIGN",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-03-26_procrastinate-outreign.jpg"
  },
  {
    "date": "2016-03-19",
    "bands": [
      "THE BUCHANNONS",
      "THYMICS"
    ],
    "rawTitle": "THE BUCHANNONS, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-03-19_the-buchannons-thymics.jpg"
  },
  {
    "date": "2016-03-12",
    "bands": [
      "KOONOOPOMANA",
      "MELLOW LIZARD"
    ],
    "rawTitle": "KOONOOPOMANA, MELLOW LIZARD",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-03-12_koonoopomana-mellow-lizard.jpg"
  },
  {
    "date": "2016-03-04",
    "bands": [
      "CORPSES",
      "COSMIC PLUNGE"
    ],
    "rawTitle": "CORPSES, COSMIC PLUNGE",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-03-04_wham-jah-kostadis-deadgum.jpg"
  },
  {
    "date": "2016-02-27",
    "bands": [
      "ΜΑΥΡΟ ΓΑΛΑ",
      "DIRTY WOMBS"
    ],
    "rawTitle": "ΜΑΥΡΟ ΓΑΛΑ, DIRTY WOMBS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-02-27_mavro-gala-dirty-wombs.jpg"
  },
  {
    "date": "2016-02-06",
    "bands": [
      "THE SUSHI KILLERS",
      "ΦΟΥΝΤΟΥΚΙΑ"
    ],
    "rawTitle": "THE SUSHI KILLERS, ΦΟΥΝΤΟΥΚΙΑ",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-02-06_the-sushi-killers-fountoukia.jpg"
  },
  {
    "date": "2016-01-30",
    "bands": [
      "KATAXNIA",
      "REPRISAL"
    ],
    "rawTitle": "KATAXNIA, REPRISAL",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-01-30_kataxnia-reprisal.jpg"
  },
  {
    "date": "2016-01-23",
    "bands": [
      "RITA MOSS",
      "LAST DAYS OF SEX"
    ],
    "rawTitle": "RITA MOSS, LAST DAYS OF SEX",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-01-23_rita-moss-last-days-of-sex_v2.jpg"
  },
  {
    "date": "2016-01-16",
    "bands": [
      "SWIM TO CAPE SHERPA",
      "SNAP"
    ],
    "rawTitle": "SWIM TO CAPE SHERPA, SNAP",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2016-01-16_swim-to-cape-sherpa-snap.jpg"
  },
  {
    "date": "2015-12-19",
    "bands": [
      "ΑΧΑΙΡΕΥΤΟΙ",
      "MANAKULA"
    ],
    "rawTitle": "ΑΧΑΙΡΕΥΤΟΙ, MANAKULA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2015-12-19_axaireftoi-mankula.jpg"
  },
  {
    "date": "2015-12-05",
    "bands": [
      "NERRVES",
      "PROJECT MK ULTRA"
    ],
    "rawTitle": "NERRVES, PROJECT MK ULTRA",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2015-12-05_nerrves-project-mk-ultra.jpg"
  },
  {
    "date": "2015-11-28",
    "bands": [
      "WISE ASTRONOMIST",
      "THYMICS"
    ],
    "rawTitle": "WISE ASTRONOMIST, THYMICS",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2015-11-28_wise-astronomist-thymics.jpg"
  },
  {
    "date": "2015-11-14",
    "bands": [
      "CHRONOBOROS",
      "BELOW THE BOTTOM"
    ],
    "rawTitle": "CHRONOBOROS, BELOW THE BOTTOM",
    "eventType": "gig",
    "location": "underground",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2015-11-14_chronoboros-below-the-bottom.jpg"
  },
  {
    "date": "2015-10-03",
    "bands": [
      "Πρώτο Πάρτυ"
    ],
    "rawTitle": "Πρώτο Πάρτυ",
    "eventType": "Party",
    "location": "georgiadis",
    "organiser": [
      "stoa60"
    ],
    "poster": "2015-2016/2015-10-03-First.jpg"
  }
];
